# Generated by Django 4.2.16 on 2024-10-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPage",
        ),
    ]
